feat(lab): add 2 lab in kotlin - #3
NikolaySavenko/Labs_etu pull request #4
Opened 2022-04-09 12:11 UTC by NikolaySavenko

closes #3

2022-04-16 09:02 UTC, a-krasilnikov requested changes
4/5

стоит поправить замечания

2022-04-16 09:02 UTC, a-krasilnikov commented on OOP/Lab2/src/main/kotlin/shapeCollectors/IShapeCollector.kt
> +interface IShapeCollector {
В Kotlin/Java не принято именовать интерфесы, начиная с `I`

2022-04-16 09:02 UTC, a-krasilnikov commented on OOP/Lab2/src/main/kotlin/shapes/Circle.kt
> +data class Circle(val radius: Double, override val borderColor: Color, override val fillColor: Color) : ColoredShape2d {
Хм, хотелось бы валидацию параметров в init блоке. А то сейчас можно создать окружность с отрицательным радиусом. Ну и для остальных фигур тоже

2022-04-16 09:02 UTC, a-krasilnikov commented on OOP/Lab2/src/main/kotlin/colors/Color.kt
> +data class Color(val primaryColor: String)
А что это за строка `primaryColor` внутри цвета?

как понять, что туда передавать? Если это должен быть цвет в формате `#000000` стоит об этом написать в документации к классу. Да и валидацию добавить.

2022-04-16 09:02 UTC, a-krasilnikov commented on OOP/Lab2/src/main/kotlin/shapeCollectors/ShapeCollector.kt
> +            throw Error("empty collector")
А зачем? Почему не вернуть null? В остальных случаях аналогично.

Да и использовать Error некорректно

2022-04-16 09:02 UTC, a-krasilnikov commented on OOP/Lab2/src/main/kotlin/shapeCollectors/ShapeCollector.kt
> +        shapes.forEach {
можно чуть проще, через `shapes.groupBy`

2022-04-23 18:08 UTC, NikolaySavenko commented on OOP/Lab2/src/main/kotlin/shapeCollectors/IShapeCollector.kt
> +interface IShapeCollector {
исправлено в [a966958](https://github.com/NikolaySavenko/Labs_etu/pull/4/commits/a966958ed85661903ecec0297a29b062de8e3b62)

2022-04-23 18:19 UTC, NikolaySavenko commented on OOP/Lab2/src/main/kotlin/colors/Color.kt
> +data class Color(val primaryColor: String)
Исправлено в [ad726d8](https://github.com/NikolaySavenko/Labs_etu/pull/4/commits/ad726d82b05773e9f6b51829f9f065e67cf5f83f)

2022-04-23 18:19 UTC, NikolaySavenko commented on OOP/Lab2/src/main/kotlin/shapes/Circle.kt
> +data class Circle(val radius: Double, override val borderColor: Color, override val fillColor: Color) : ColoredShape2d {
Исправлено в [ad726d8](https://github.com/NikolaySavenko/Labs_etu/pull/4/commits/ad726d82b05773e9f6b51829f9f065e67cf5f83f)

2022-04-23 18:23 UTC, NikolaySavenko commented on OOP/Lab2/src/main/kotlin/shapeCollectors/ShapeCollector.kt
> +            throw Error("empty collector")
Исправлено в [3bc8b41](https://github.com/NikolaySavenko/Labs_etu/pull/4/commits/3bc8b41d8757e59e5344ca7674aa06f9fb4be036)

2022-04-23 18:52 UTC, NikolaySavenko commented on OOP/Lab2/src/main/kotlin/shapeCollectors/ShapeCollector.kt
> +        shapes.forEach {
Исправлено в [fdfb965](https://github.com/NikolaySavenko/Labs_etu/pull/4/commits/fdfb965089ff83d83e21f51235143f99e2d1b611)

2022-05-11 17:18 UTC, a-krasilnikov approved these changes

2022-05-14 18:37 UTC, merged

2022-05-15 14:21 UTC, a-krasilnikov approved these changes